### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Chalta**
Readers can't apply labels - changed issue submission details.
Hinted the people commands to display natural language RegEx flexibility.
Organized commands logically.
Added pypco reference.

### CODE REVIEW

**Comment by Chalta** [comment]
Travis CI is correct. README.md is not valid python code. 

:expressionless:

**Comment by pastorhudson** [comment]
Done! Thank you for this!

**Comment by Chalta** [comment]
Thanks for approving, but it doesn't look like the commit was merged.

**Comment by pastorhudson** [comment]
That's better!

**Pull request merged**
