### PR TITLE
Added response and function for fetching team status

### PR DESCRIPTION
**Pull request by calebdinsmore**
For issue #105 

I added a function in pcoservices to respond to queries of the form:

> who is scheduled on the <team name> team <when>?

e.g. 
> "who is scheduled on the Downtown Band team on Sunday at 6PM?

If you specify a time, it will try to find the team for that precise time--if you do not, it will simply try to match the team for the day provided.

I tried to mimic other files in form (and I removed some unnecessary whitespace).

### CODE REVIEW

**Comment by pastorhudson** [comment]
Thanks so much for this! Could you add instructions to the readme?

**Comment by ecclesiatech** [comment]
I added to the Readme. Caleb, feel free to review and add / edit as necessary.

**Comment by calebdinsmore** [comment]
@ecclesiatech where are the changes you made?

**Comment by ecclesiatech** [comment]
on the dev branch readme file?

**Comment by calebdinsmore** [comment]
I'm sorry--can you link me to it? I looked on my dev, @pastorhudson's dev, and your dev (so many forks, haha), and I can't see changes or any recent commits with changes. Are you certain you pushed?

**Comment by ecclesiatech** [comment]
Ah, it's still listed as a pull request. hasn't been committed yet. https://github.com/pastorhudson/pcobot/pull/130

**Pull request merged**
